
<?php
require 'dbConnect.php';
date_default_timezone_set('UTC');
$ActualDate = date('Y-m-d H:i:s');
$anneActu = substr($ActualDate,0,4);
$HourActu = substr($ActualDate,10,3);
$MinActu = substr($ActualDate,14,2);
$query='';
$pdoResult;

$request = $_REQUEST;
$numeroSolb = $request["numeroSolb"];
$anneeSolb = $request["anneeSolb"];
json_encode("text ");
if(trim($numeroSolb)!="" && trim($anneeSolb)!="")
{


  $query1="SELECT  * FROM `sbirth` WHERE `numero`=? AND `annee`=?";
$pdoResult1 = $pdoConnect->prepare($query1);
$pdoResult1->execute(array($numeroSolb,$anneeSolb));

$result1=$pdoResult1->fetch();
if($pdoResult1->rowCount()>0)
{
$dataSBirth = array(
"numero"=> $result1["numero"],
"annee"=> $result1["annee"],
"prenom_ar"=> $result1["prenom_ar"],
"prenom"=> $result1["prenom"],
"nom_ar"=> $result1["nom_ar"],
"nom"=> $result1["nom"],
"prenom_tora_ar"=> $result1["prenom_tora_ar"],
"prenom_tora"=> $result1["prenom_tora"],
"nom_tora_ar"=> $result1["nom_tora_ar"],
"nom_tora"=> $result1["nom_tora"],
"sex"=> $result1["sex"],
"lieu_naiss_ar"=> $result1["lieu_naiss_ar"],
"lieu_naiss"=> $result1["lieu_naiss"],
"commune_ar"=> $result1["commune_ar"],
"commune"=> $result1["commune"],
"date_naiss_miladi"=> $result1["date_naiss_miladi"],
"date_naiss_hijri"=> $result1["date_naiss_hijri"],
"date_naiss_miladi_ar"=> $result1["date_naiss_miladi_ar"],
"date_naiss_hijri_ar"=> $result1["date_naiss_hijri_ar"],
"date_naiss_miladi_fr"=> $result1["date_naiss_miladi_fr"],
"date_naiss_hijri_fr"=> $result1["date_naiss_hijri_fr"],
"heure"=> $result1["heure"],
"min_naiss"=> $result1["min_naiss"],
"nationalite_ar"=> $result1["nationalite_ar"],
"nationalite"=> $result1["nationalite"],
"tora_deces_ar"=> $result1["tora_deces_ar"],
"tora_deces"=> $result1["tora_deces"],
"nom_pere_ar"=> $result1["nom_pere_ar"],
"nom_pere"=> $result1["nom_pere"],
"nom_pere_ar"=> $result1["nom_pere_ar"],
"nom_pere"=> $result1["nom_pere"],
"nom_pere_tora_ar"=> $result1["nom_pere_tora_ar"],
"nom_pere_tora"=> $result1["nom_pere_tora"],
"nom_pere_tora_ar"=> $result1["nom_pere_tora_ar"],
"nom_pere_tora"=> $result1["nom_pere_tora"],
"dead_pere"=> $result1["dead_pere"],
"date_naiss_pere_miladi"=> $result1["date_naiss_pere_miladi"],
"date_naiss_pere_hijri"=> $result1["date_naiss_pere_hijri"],
"date_naiss_pere_miladi_ar"=> $result1["date_naiss_pere_miladi_ar"],
"date_naiss_pere_hijri_ar"=> $result1["date_naiss_pere_hijri_ar"],
"date_naiss_pere_miladi_fr"=> $result1["date_naiss_pere_miladi_fr"],
"date_naiss_pere_hijri_fr"=> $result1["date_naiss_pere_hijri_fr"],
"lieu_naiss_pere_ar"=> $result1["lieu_naiss_pere_ar"],
"lieu_naiss_pere"=> $result1["lieu_naiss_pere"],
"nationalite_pere_ar"=> $result1["nationalite_pere_ar"],
"nationalite_pere"=> $result1["nationalite_pere"],
"profession_pere_ar"=> $result1["profession_pere_ar"],
"profession_pere"=> $result1["profession_pere"],
"niveau_scol_pere_ar"=> $result1["niveau_scol_pere_ar"],
"niveau_pere_scol"=> $result1["niveau_pere_scol"],
"nom_mere_ar"=> $result1["nom_mere_ar"],
"nom_mere"=> $result1["nom_mere"],
"nom_mere_tora_ar"=> $result1["nom_mere_tora_ar"],
"nom_mere_tora"=> $result1["nom_mere_tora"],
"dead_mere"=> $result1["dead_mere"],
"date_naiss_mere_miladi"=> $result1["date_naiss_mere_miladi"],
"date_naiss_mere_hijri"=> $result1["date_naiss_mere_hijri"],
"date_naiss_mere_miladi_ar"=> $result1["date_naiss_mere_miladi_ar"],
"date_naiss_mere_hijri_ar"=> $result1["date_naiss_mere_hijri_ar"],
"date_naiss_mere_miladi_fr"=> $result1["date_naiss_mere_miladi_fr"],
"date_naiss_mere_hijri_fr"=> $result1["date_naiss_mere_hijri_fr"],
"lieu_naiss_mere_ar"=> $result1["lieu_naiss_mere_ar"],
"lieu_naiss_mere"=> $result1["lieu_naiss_mere"],
"nationalite_mere_ar"=> $result1["nationalite_mere_ar"],
"nationalite_mere"=> $result1["nationalite_mere"],
"profession_mere_ar"=> $result1["profession_mere_ar"],
"profession_mere"=> $result1["profession_mere"],
"niveau_scol_mer_ar"=> $result1["niveau_scol_mer_ar"],
"niveau_scol_mer"=> $result1["niveau_scol_mer"],
"ordre_naiss"=> $result1["ordre_naiss"],
"adresse_parent_ar"=> $result1["adresse_parent_ar"],
"adresse_parent"=> $result1["adresse_parent"],
"selon_ar"=> $result1["selon_ar"],
"selon"=> $result1["selon"],
"age_num_ar"=> $result1["age_num_ar"],
"age_num_fr"=> $result1["age_num_fr"],
"adresse_annonceur_ar"=> $result1["adresse_annonceur_ar"],
"adresse_annonceur"=> $result1["adresse_annonceur"],
"date_annonce_miladi"=> $result1["date_annonce_miladi"],
"date_annonce_hijri"=> $result1["date_annonce_hijri"],
"date_annonce_miladi_ar"=> $result1["date_annonce_miladi_ar"],
"date_annonce_hijri_ar"=> $result1["date_annonce_hijri_ar"],
"date_annonce_miladi_fr"=> $result1["date_annonce_miladi_fr"],
"date_annonce_hijri_fr"=> $result1["date_annonce_hijri_fr"],
"par_nous_ar"=> $result1["par_nous_ar"],
"par_nous"=> $result1["par_nous"],
"officier_etat_civil_ar"=> $result1["officier_etat_civil_ar"],
"officier_etat_civil"=> $result1["officier_etat_civil"]
);
}else {
  $dataSBirth = array(
  "prenom_ar"=> "",
  "prenom"=>"" ,
  "nom_ar"=>"" ,
  "nom"=> "",
  "prenom_tora_ar"=> "",
  "prenom_tora"=> "",
  "nom_tora_ar"=> "",
  "nom_tora"=> "",
  "sex"=> "",
  "lieu_naiss_ar"=> "",
  "lieu_naiss"=> "",
  "commune_ar"=> "",
  "commune"=> "",
  "date_naiss_miladi"=>"" ,
  "date_naiss_hijri"=> "",
  "date_naiss_miladi_ar"=>"" ,
  "date_naiss_hijri_ar"=>"" ,
  "date_naiss_miladi_fr"=> "",
  "date_naiss_hijri_fr"=> "",
  "heure"=> "",
  "min_naiss"=> "",
  "nationalite_ar"=> "",
  "nationalite"=> "",
  "tora_deces_ar"=> "",
  "tora_deces"=> "",
  "prenom_pere_ar"=> "",
  "prenom_pere"=>"" ,
  "nom_pere_ar"=>"" ,
  "nom_pere"=>"" ,
  "prenom_pere_tora_ar"=> "",
  "prenom_pere_tora"=> "",
  "nom_pere_tora_ar"=> "",
  "nom_pere_tora"=> "",
  "dead_pere"=> "",
  "date_naiss_pere_miladi"=> "",
  "date_naiss_pere_hijri"=>"" ,
  "date_naiss_pere_miladi_ar"=> "",
  "date_naiss_pere_hijri_ar"=>"",
  "date_naiss_pere_miladi_fr"=> "",
  "date_naiss_pere_hijri_fr"=>"" ,
  "lieu_naiss_pere_ar"=>"",
  "lieu_naiss_pere"=> "",
  "nationalite_pere_ar"=> "",
  "nationalite_pere"=> "",
  "profession_pere_ar"=> "",
  "profession_pere"=> "",
  "niveau_scol_pere_ar"=> "",
  "niveau_pere_scol"=> "",
  "nom_mere_ar"=> "",
  "nom_mere"=>"" ,
  "nom_mere_tora_ar"=> "",
  "nom_mere_tora"=> "",
  "dead_mere"=> "",
  "date_naiss_mere_miladi"=> "",
  "date_naiss_mere_hijri"=> "",
  "date_naiss_mere_miladi_ar"=> "",
  "date_naiss_mere_hijri_ar"=> "",
  "date_naiss_mere_miladi_fr"=> "",
  "date_naiss_mere_hijri_fr"=> "",
  "lieu_naiss_mere_ar"=> "",
  "lieu_naiss_mere"=> "",
  "nationalite_mere_ar"=>"" ,
  "nationalite_mere"=> "",
  "profession_mere_ar"=> "",
  "profession_mere"=>"",
  "niveau_scol_mer_ar"=> "",
  "niveau_scol_mere"=> "",
  "ordre_naiss"=> "",
  "adresse_parent_ar"=> "",
  "adresse_parent"=> "",
  "selon_ar"=> "",
  "selon"=> "",
  "age_num_ar"=> "",
  "age_num_fr"=> "",
  "adresse_annonceur_ar"=> "",
  "adresse_annonceur"=> "",
  "date_annonce_miladi"=> "",
  "date_annonce_hijri"=> "",
  "date_annonce_miladi_ar"=> "",
  "date_annonce_hijri_ar"=> "",
  "date_annonce_miladi_fr"=> "",
  "date_annonce_hijri_fr"=>"" ,
  "par_nous_ar"=> "",
  "par_nous"=>"" ,
  "officier_etat_civil_ar"=>"" ,
  "officier_etat_civil"=>""
  );
}
}
echo json_encode($dataSBirth);

?>
